#!/usr/bin/env python3
"""
03c_hecras_setup.py - HEC-RAS 2D Project Setup & Automation
Drone Drainage Analysis Pipeline

Creates a HEC-RAS 2D rain-on-grid project from drone DSM data,
runs GPU-accelerated storm simulations, and extracts results.

This script:
1. Creates HEC-RAS project structure (terrain, geometry, plans)
2. Generates precipitation boundary conditions for each scenario
3. Runs simulations via command line (GPU-accelerated)
4. Extracts depth/velocity results from HDF5 output

Prerequisites:
- HEC-RAS 6.6 installed at C:\\Program Files (x86)\\HEC\\HEC-RAS\\6.6\\
- NVIDIA GPU with OpenCL support (for GPU acceleration)
- Python packages: h5py, rashdf, numpy, rasterio

Usage:
    python 03c_hecras_setup.py --dsm terrain.tif --output ./hecras --config config.json

NOTE: The initial mesh creation must be done in RAS Mapper GUI.
This script prepares all files and provides step-by-step instructions
for the one-time GUI setup, then automates everything else.
"""

import os
import sys
import json
import shutil
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, List

try:
    import numpy as np
    import h5py
except ImportError:
    print("ERROR: Required packages not found. Install: pip install numpy h5py")
    sys.exit(1)

# =============================================================================
# Configuration
# =============================================================================

HECRAS_DIR = Path(r"C:\Program Files (x86)\HEC\HEC-RAS\6.6")
HECRAS_EXE = HECRAS_DIR / "Ras.exe"

PROJECT_NAME = "SampleSite_Drainage"

# Rainfall scenarios (same as r.sim.water for comparison)
RAINFALL_SCENARIOS = [
    {"label": "05in", "inches": 0.5, "duration_hr": 1.0},
    {"label": "10in", "inches": 1.0, "duration_hr": 1.0},
    {"label": "15in", "inches": 1.5, "duration_hr": 1.0},
    {"label": "20in", "inches": 2.0, "duration_hr": 1.0},
]

# SCS Type II storm distribution (cumulative fractions at time intervals)
# For a 1-hour storm, we use a simplified distribution
SCS_TYPE2_1HR = [
    (0.0, 0.000),
    (0.1, 0.020),
    (0.2, 0.050),
    (0.3, 0.100),
    (0.4, 0.330),  # peak intensity period
    (0.5, 0.663),
    (0.6, 0.800),
    (0.7, 0.870),
    (0.8, 0.920),
    (0.9, 0.960),
    (1.0, 1.000),
]


def create_project_structure(project_dir: Path, terrain_path: Path,
                             config: dict) -> Dict:
    """Create HEC-RAS project directory structure and files."""

    project_dir.mkdir(parents=True, exist_ok=True)
    terrain_dir = project_dir / "Terrain"
    terrain_dir.mkdir(exist_ok=True)

    community = config.get('community_name', 'Study_Area')
    prj_name = PROJECT_NAME

    # Copy terrain to project
    terrain_dest = terrain_dir / "terrain.tif"
    if not terrain_dest.exists():
        shutil.copy2(str(terrain_path), str(terrain_dest))
        print(f"  Copied terrain to {terrain_dest}")

    # Create project file (.prj)
    prj_path = project_dir / f"{prj_name}.prj"
    prj_content = f"""Proj Title={community} Drainage Assessment
Current Plan=p01
Default Exp/Contr=0.3,0.1
English Units
Geom File=g01
Unsteady File=u01
Plan File=p01
Y Axis Title=Elevation
X Axis Title=Main Channel Distance
BEGIN DESCRIPTION:
HEC-RAS 2D rain-on-grid model for {community}
Terrain: Pix4D drone DSM at 30cm resolution
Generated by drainage-analysis pipeline
END DESCRIPTION:
DSS Start Date=
DSS Start Time=
DSS End Date=
DSS End Time=
DSS Export Filename=
DSS Export Rating Curves= 0
DSS Export Rating Curve Sorted= 0
DSS Export Volume Flow Curves= 0
DSSExportStageTW= 0
Write HDF5 Tables= 1
Use Unsteady= -1
"""
    prj_path.write_text(prj_content)

    # Create plan file (.p01)
    plan_path = project_dir / f"{prj_name}.p01"
    plan_content = f"""Plan Title=Storm Simulation 0.5-2.0 inch
Program Version=6.60
Short Identifier=Storm_Sim
Simulation Date=01JAN2026,0000,01JAN2026,0600
Geom File=g01
Flow File=u01
Subcritical Approach= 0
Supercritical Approach= 0
Run HTab= 0
Run UNet= -1
Run Sediment= 0
Run PostProcess= -1
Run WQNet= 0
Run RASMapper= -1
UNET Use Existing IB Tables= 0
UNET D1 Cores= 0
UNET D2 Cores= 0
UNET Use GPU= -1
UNET 2D Eq= 2
UNET D2 Name= SampleSite2D
2D Cell Size=  0.5
2D Gate Param A= 1
2D Gate Param B= 1
Log Output Level= 10
Computation Interval=1SEC
Output Interval=5MIN
Instantaneous Interval=5MIN
Mapping Interval=1MIN
Run Flags= dsmt
Write IC File= 0
Echo Input= 0
Echo Parameters= 0
Echo Output= 0
Write Detailed= 0
"""
    plan_path.write_text(plan_content)

    # Create geometry file (.g01) - placeholder, mesh created in RAS Mapper
    geom_path = project_dir / f"{prj_name}.g01"
    geom_content = f"""Geom Title=SampleSite 2D Geometry
Program Version=6.60
Viewing Rectangle= 0 , 0 , 0 , 0

2D Flow Area=SampleSite2D
Storage Area Conn=0

BEGIN DESCRIPTION:
2D flow area for Sample Lakeside drainage analysis.
Terrain from Pix4D drone DSM.
END DESCRIPTION:
"""
    geom_path.write_text(geom_content)

    # Create unsteady flow file (.u01) with precipitation boundary
    flow_path = project_dir / f"{prj_name}.u01"
    flow_content = f"""Flow Title=Rainfall Scenarios
Program Version=6.60
Use Restart= 0
Precipitation=SampleSite2D
Precip Type=Uniform
Precip Method=Specified Hyetograph
"""

    # Add hyetograph for the largest scenario (2.0 inch)
    # In practice, we'd create separate plans per scenario
    total_inches = 2.0
    flow_content += f"Precip Total={total_inches}\n"
    flow_content += "Precip Time Interval=6MIN\n"

    # Generate incremental rainfall from SCS Type II
    flow_content += "Precip Hyetograph=\n"
    prev_frac = 0
    for t, frac in SCS_TYPE2_1HR:
        incr = (frac - prev_frac) * total_inches
        flow_content += f"  {incr:.4f}\n"
        prev_frac = frac

    # Downstream boundary - normal depth
    flow_content += """
Boundary Location=SampleSite2D,,Downstream,,
Interval=1MIN
Normal Depth=0.005
"""
    flow_path.write_text(flow_content)

    print(f"  Project files created in {project_dir}")

    return {
        'project_dir': str(project_dir),
        'project_file': str(prj_path),
        'terrain': str(terrain_dest),
        'geometry': str(geom_path),
        'plan': str(plan_path),
        'flow': str(flow_path)
    }


def generate_gui_instructions(project_dir: Path, config: dict) -> str:
    """Generate step-by-step instructions for the one-time GUI setup."""

    community = config.get('community_name', 'Sample Lakeside')
    prj_name = PROJECT_NAME
    prj_file = project_dir / f"{prj_name}.prj"

    instructions = f"""
================================================================================
HEC-RAS 2D Setup Instructions for {community}
================================================================================

The project files have been created. You need to complete the mesh setup
in RAS Mapper (one-time process), then all subsequent runs can be automated.

STEP 1: Open the Project
  - Launch HEC-RAS 6.6
  - File > Open Project > {prj_file}

STEP 2: Import Terrain (RAS Mapper)
  - Click "RAS Mapper" button (or View > RAS Mapper)
  - Right-click "Terrain" in the layer tree > Create a New Terrain
  - Name it "SampleSite_Terrain"
  - Click "+" to add a file > Browse to:
    {project_dir / 'Terrain' / 'terrain.tif'}
  - Click "Create" — this converts the GeoTIFF to HEC-RAS HDF5 terrain

STEP 3: Create 2D Flow Area
  - In RAS Mapper, expand "Geometries" > right-click "SampleSite2D"
  - If not visible, right-click Geometries > Add New Geometry > name "g01"
  - Add 2D Flow Area:
    - Right-click the geometry > "Add 2D Flow Area"
    - Name: "SampleSite2D"
    - Draw a polygon around the LAND area (exclude the lake)
    - TIP: Use the parcel boundaries as a guide for where to draw
    - Set default cell size: 0.5m (for property-level detail)
      or 1.0m (for faster computation)

STEP 4: Generate Computational Mesh
  - Right-click the 2D flow area > "Generate Computational Mesh"
  - This creates the computational grid
  - Expected: ~500K-2M cells at 0.5m, ~125K-500K at 1.0m

STEP 5: Add Breaklines (Optional but Recommended)
  - Add breaklines along:
    - Roads (force mesh to align with road edges)
    - Building footprints (force mesh around structures)
    - Any known drainage channels or swales
  - Right-click 2D area > "Add Breakline" > draw or import

STEP 6: Set Manning's n (Roughness)
  - In RAS Mapper, right-click geometry > "Manning's n Values"
  - Set default: 0.035 (mixed residential)
  - Or create a land cover layer with varying roughness

STEP 7: Set Precipitation Boundary Condition
  - In the main HEC-RAS window: Edit > Unsteady Flow Data
  - The precipitation BC is already configured in the .u01 file
  - Verify: "SampleSite2D" shows as a Precipitation boundary

STEP 8: Set Downstream Boundary
  - In Unsteady Flow Data, add a downstream boundary:
    - Draw a boundary line at the lake edge of the 2D area
    - Set type: "Normal Depth" with friction slope 0.005

STEP 9: Configure GPU Computation
  - Edit > Plan Data > Options > Computation Options
  - Under "2D Computation Options":
    - Change compute device to "NVIDIA RTX 3500 Ada" (or your GPU name)
    - This enables OpenCL GPU acceleration

STEP 10: Run the Simulation
  - Click "Run" > "Compute"
  - Or use the automated script (after this one-time setup):
    "{HECRAS_EXE}" -c "{prj_file}"

STEP 11: View Results
  - In RAS Mapper: Results > Depth, Velocity, WSE
  - Enable animation to see flooding progression
  - Export depth grids: Results > Export > GeoTIFF

================================================================================
After completing Steps 1-9 once, the automation script can:
  - Modify rainfall amounts in the .u01 file
  - Run simulations headlessly via command line
  - Extract results from the HDF5 output
  - Generate reports automatically
================================================================================
"""
    return instructions


def run_hecras(project_file: Path, verbose: bool = True) -> bool:
    """Run HEC-RAS simulation via command line."""
    if not HECRAS_EXE.exists():
        print(f"ERROR: HEC-RAS not found at {HECRAS_EXE}")
        return False

    cmd = [str(HECRAS_EXE), "-c", str(project_file)]
    if verbose:
        print(f"  Running: {' '.join(cmd)}")

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)

    if result.returncode == 0:
        if verbose:
            print("  HEC-RAS computation completed successfully")
        return True
    else:
        if verbose:
            print(f"  HEC-RAS computation failed (exit code {result.returncode})")
            if result.stderr:
                print(f"  stderr: {result.stderr[:500]}")
        return False


def extract_results(project_dir: Path, plan_name: str = "p01",
                    verbose: bool = True) -> Dict:
    """Extract simulation results from HEC-RAS HDF5 output."""
    results = {}

    plan_hdf = project_dir / f"{PROJECT_NAME}.{plan_name}.hdf"
    if not plan_hdf.exists():
        if verbose:
            print(f"  No results HDF found: {plan_hdf}")
        return results

    try:
        import rashdf
        # Use rashdf to extract results
        if verbose:
            print(f"  Reading results from {plan_hdf}")

        with h5py.File(str(plan_hdf), 'r') as f:
            # Navigate the HDF5 structure
            if 'Results' in f and 'Unsteady' in f['Results']:
                unsteady = f['Results']['Unsteady']
                if 'Output' in unsteady:
                    output = unsteady['Output']
                    if 'Output Blocks' in output:
                        # Get max depth across time
                        # The structure varies by HEC-RAS version
                        pass

            results['hdf_path'] = str(plan_hdf)
            results['status'] = 'results_available'

    except Exception as e:
        if verbose:
            print(f"  Error reading results: {e}")
        results['error'] = str(e)

    return results


# =============================================================================
# Main
# =============================================================================

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Set up HEC-RAS 2D project for storm simulation'
    )
    parser.add_argument('--dsm', required=True, help='Path to terrain GeoTIFF (resampled to 30cm)')
    parser.add_argument('--config', '-c', help='Community config JSON')
    parser.add_argument('--output', '-o', required=True, help='HEC-RAS project directory')
    parser.add_argument('--run', action='store_true',
                        help='Run simulation after setup (requires mesh to be created in GUI first)')

    args = parser.parse_args()

    config = {}
    if args.config:
        p = Path(args.config)
        if p.exists():
            with open(p) as f:
                config = json.load(f)

    project_dir = Path(args.output)
    terrain_path = Path(args.dsm)

    print(f"\n{'='*60}")
    print("HEC-RAS 2D Project Setup")
    print(f"{'='*60}\n")

    # Verify HEC-RAS installation
    if not HECRAS_EXE.exists():
        print(f"ERROR: HEC-RAS not found at {HECRAS_EXE}")
        print("Install HEC-RAS 6.6 from: https://www.hec.usace.army.mil/software/hec-ras/")
        sys.exit(1)

    print(f"  HEC-RAS: {HECRAS_EXE}")
    print(f"  Terrain: {terrain_path}")
    print(f"  Project: {project_dir}")

    # Create project
    files = create_project_structure(project_dir, terrain_path, config)

    # Generate and display instructions
    instructions = generate_gui_instructions(project_dir, config)
    print(instructions)

    # Save instructions to file
    instructions_path = project_dir / "SETUP_INSTRUCTIONS.txt"
    instructions_path.write_text(instructions)
    print(f"Instructions saved to: {instructions_path}")

    # Optionally run (only works after GUI mesh setup)
    if args.run:
        prj_file = Path(files['project_file'])
        geom_hdf = project_dir / f"{PROJECT_NAME}.g01.hdf"
        if geom_hdf.exists():
            print("\nRunning simulation...")
            success = run_hecras(prj_file)
            if success:
                results = extract_results(project_dir)
                print(f"Results: {results}")
        else:
            print("\nCannot run yet — mesh not created.")
            print("Complete the GUI setup steps first, then re-run with --run")

    # Save setup metadata
    setup_meta = {
        'timestamp': datetime.now().isoformat(),
        'hecras_version': '6.6',
        'project_dir': str(project_dir),
        'terrain': str(terrain_path),
        'files': files,
        'scenarios': RAINFALL_SCENARIOS,
        'status': 'project_created_awaiting_mesh_setup'
    }
    meta_path = project_dir / "setup_metadata.json"
    with open(meta_path, 'w') as f:
        json.dump(setup_meta, f, indent=2)

    print(f"\n{'='*60}")
    print("Project created. Complete GUI setup, then automation takes over.")
    print(f"{'='*60}\n")


if __name__ == '__main__':
    main()
